package zina_eliran.app.API;

import android.util.Log;

import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;

import java.util.UUID;

import zina_eliran.app.API.Listeners.GetUserEventListener;
import zina_eliran.app.BusinessEntities.BEResponse;
import zina_eliran.app.BusinessEntities.BEResponseStatusEnum;
import zina_eliran.app.BusinessEntities.BEUser;
import zina_eliran.app.BusinessEntities.CMNLogHelper;

/**
 * Created by Zina K on 9/10/2016.
 */
public class DAL {

    private static Firebase rootRef = new Firebase("https://trainingstudiofb.firebaseio.com");
    private static Firebase usersRef;
//    private static Firebase usersRef = rootRef.child("Users");
//    private static Firebase trainingsRef= rootRef.child("Trainings");
//    Firebase ref = new Firebase("https://docs-examples.firebaseio.com/android/saving-data/fireblog");

    public DAL(){
//        Firebase usersRef = rootRef.child("Users");
////        Firebase trainingsRef = rootRef.child("Trainings");
//
//        BEUser testUser = new BEUser();
//        testUser.setName("Eliran");
//        testUser.setEmail("eliran@com");
//        testUser.setVerificationCode("12345");
////        registerUser(testUser);
//        Firebase newUserRef = usersRef.push();
//        newUserRef.setValue(testUser);
//        // Get the unique ID generated by push()
//        String generatedUniqueID = newUserRef.getKey();
//        testUser.setId(generatedUniqueID);
//
//        //Save user including UUID
//        newUserRef.setValue(testUser);
//        int i = 1;

        usersRef = rootRef.child("Users");



//        Firebase childRef = rootRef.child("Users2");
//        childRef.setValue("Zina2");
//        Firebase training = rootRef.child("Training");
//        training.push("NewTrainig");
//        training.setValue("NewTraining");
        // Generate a reference to a new location and add some data using push()

        Firebase newUserRef = usersRef.push();
        // Add some data to the new location
        BEUser user = new BEUser();
        user.setEmail("dima@ctera.com");
        user.setName("blablaeeee");
        user.setVerificationCode("12665");

        String generatedUniqueID = newUserRef.getKey();
        user.setId(generatedUniqueID);
        newUserRef.setValue(user);
        int i = 1;
        getUserByUID(generatedUniqueID, user);


    }

//    public static void registerUser(BEUser user) {
//        try{
//            //Set location to push
//            Firebase a = usersRef.getRef();
//            Firebase newUserRef = usersRef.push();
//
//            // Get the unique ID generated by push()
//            String generatedUniqueID = newUserRef.getKey();
//            user.setId(generatedUniqueID);
//
//            //Save user including UUID
//            newUserRef.setValue(user, new Firebase.CompletionListener() {
//                @Override
//                public void onComplete(FirebaseError firebaseError, Firebase firebase) {
//                    int a = 1;
//                }
//            });
//        } catch (Exception e) {
//
//            CMNLogHelper.logError("DAL", e.getMessage());
//        }
//
//
//    }

    private BEResponse getUserByUID(String uid, BEUser user){
        final BEUser[] resUser = {new BEUser()};
        Firebase singleUserRef = usersRef.child(uid);
//        GetUserEventListener listener = new GetUserEventListener();

//        singleUserRef.addListenerForSingleValueEvent(listener);
        singleUserRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                BEUser user = dataSnapshot.getValue(BEUser.class);
                Log.e("DAL", "Listener Zina");
                Log.e("DAL", user.getName());

                resUser[0] = user;
                int i = 1;
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        });

//        singleUserRef.setValue(user);

//        String value = listener.getRes().getEntity().toString();
//        int a = 1;
        return null;
    }
}
